language: node_js

node_js:
   - 8

branches:
  only:
    - master

install:
  - npm install -g codecov
  - npm install -g nyc
  - npm install -g ava

notifications:
  email: false

script:
  - npm test

after_success:
  - npm run report-coverage
