language: node_js

node_js:
   - 8

branches:
  only:
    - master

install:
  - npm install

notifications:
  email: false

script:
  - npm test

after_success:
  - ls -la
  - cd coverage && ls -la
  - npm run report-coverage
  - ls -la
  - cd coverage && ls -la

sudo: true