language: node_js

node_js:
   - 8

branches:
  only:
    - master

install:
  - npm install -g codecov
  - npm install -g nyc

notifications:
  email: false

after_success:
  - npm run report-coverage
